#!/bin/bash
# version:1.21 date:20220825 author:wangshuo

# set -x
VERSION=1.21
REVERSE="~"
SHELL_RC="~/.bashrc"

project=$*
REPO_DIR=".repo"
CUR_DIR=`pwd`
HOME_DIR=`echo $HOME`
INSTALL_PATH="~/bin"
SCRIPT_PATH=$(cd `dirname $0`; pwd)
SCRIPT_NAME="$(basename $0)"
OLD_DIR=""
repo=""
GREP_STRING=""

function Usage() {
    echo -e "\033[33mUsage: $SCRIPT_NAME [project path]\033[0m"
    echo -e "\033[37m   eg: $SCRIPT_NAME preloader (return path within preloader)\033[0m"
    echo -e "\033[33mUsage: $SCRIPT_NAME ${REVERSE}[project path]\033[0m"
    echo -e "\033[37m   eg: $SCRIPT_NAME custom ${REVERSE}trustzone (return custom but without trustzone)\033[0m"
    echo -e "\033[33mUsage: $SCRIPT_NAME ~ (return to top of your project)\033[0m"
    echo -e "\n\033[33m[-h] help\033[0m"
    echo -e "\033[33m[-v] version\033[0m"
    echo -e "\033[33m[-i] install the $SCRIPT_NAME\033[0m"
    echo -e "\033[33m[-u] upgrade the $SCRIPT_NAME\033[0m"
}

function Upgrade() {

    git_dir="/tmp/cdr"
    git clone https://github.com/WSure00/cdr.git $git_dir

    if [ $? -ne 0 ];then
        echo "git clone failed, please check git"
        echo "error: git clone https://github.com/WSure00/cdr.git $git_dir"
    else
        target_version=`grep "VERSION=" $git_dir/cdr | awk -F'=' 'NR==1{print$2}'`
        if [ `expr $VERSION \>\= $target_version` -eq 0 ];then
            echo -e "\nlocal version is $VERSION, latest version is $target_version"
            echo "--------upgrading--------"
            echo "..."
            mv $git_dir/cdr $SCRIPT_PATH/
            rm -rf $git_dir
            echo "--------upgrading success--------"
        else
            echo -e "\nalready the latest version: $VERSION"
            rm -rf $git_dir
        fi
    fi
}

function findrepo(){

    while [ "$CUR_DIR" != "$OLD_DIR" ] && [ -z "$repo" ]
    do
        repo="$CUR_DIR/$REPO_DIR"
        if [ ! -d "$repo" ];then
            repo=""
            OLD_DIR=$CUR_DIR
            CUR_DIR=`dirname $CUR_DIR`
        fi
    done

}

function grep_string(){

        for i in `echo $project`;do
            if [ ${i:0:1} = "$REVERSE" ];then
                GREP_STRING=${GREP_STRING}"grep -iv ${i:1} |"
            else
                GREP_STRING=${GREP_STRING}"grep -i $i |"
            fi
        done

}

function Install(){

    mkdir -p ~/bin && cp $SCRIPT_NAME ~/bin/ && echo -e "mkdir $INSTALL_PATH \nmove $SCRIPT_NAME to $INSTALL_PATH/"
    shell_string=`eval "cat $SHELL_RC | grep \"export PATH\" | grep \"$INSTALL_PATH\" | grep -v \"#\""`
    if [ -n "$shell_string" ];then
        echo "PATH already exist!"
    else
        eval "echo \"export PATH=\\\$PATH:$INSTALL_PATH\" >> $SHELL_RC"
        echo "export PATH=\$PATH:$INSTALL_PATH >> $SHELL_RC"
    fi

    shell_string=`eval "cat $SHELL_RC | grep \"alias $SCRIPT_NAME\" | grep \"source $INSTALL_PATH/$SCRIPT_NAME\" | grep -v \"#\""`
    if [ -n "$shell_string" ];then
        echo "alias already exist!"
    else
        eval "echo \"alias $SCRIPT_NAME='source $INSTALL_PATH/$SCRIPT_NAME'\" >> $SHELL_RC"
        echo "alias $SCRIPT_NAME='source $INSTALL_PATH/$SCRIPT_NAME' >> $SHELL_RC"
    fi

    echo -e "\033[33m-----install successful!------\033[0m"
    echo -e "please run:"
    echo -e "\033[33m          source  $SHELL_RC\033[0m"
}

findrepo
if [ "$#" -gt "0" ];then
    if [ "${1:0:1}" != "-" ];then
        if [ "$CUR_DIR" != "/" ];then
            if [ "$1" != "~" ] && [ "$1" != "$HOME_DIR" ];then
                SHELL_VERSION=`ps -ef | grep $(echo $$) | grep -v grep | grep -v ps `

                grep_string
                shell_string="repo list | $GREP_STRING awk '{print \$0}'"
                repository="`eval $shell_string`"
                project_sum=`echo "$repository" | awk 'END{if($0!="")print NR}'`

                if [ -z "$project_sum" ];then
                    echo -e "\033[33merror: cannot find $*\033[0m"
                elif [ "$project_sum" -gt "1" ];then

                    color=$(echo "$repository" | awk '{print NR". "$0}' | sed 's/:/--->/g')
                    for c in `echo $project`;do
                        color=$(echo "$color" | sed 's#'${c}'#\\033[01m\\033[31m'${c}'\\033[0m#g')
                    done
                    echo -e "$color"
                    echo ""

                    if [ -n "`echo $SHELL_VERSION | grep zsh`" ];then
                        vared -p "Please select a number of directory: " -c choice
                    else
                        read -p "Please select a number of directory: " choice
                    fi

                    if [ $choice -le $project_sum ] && [ $choice -gt 0 ];then
                        dest_project="`echo "$repository" | awk 'NR=="'$choice'"{print$1}'`"
                        echo "path : $CUR_DIR/$dest_project"
                        cd $CUR_DIR/$dest_project
                    else
                        echo -e "\033[33merror: number should between 1 ~ ${project_sum}\033[0m"
                    fi
                        unset choice

                elif [ "$project_sum" -gt "0" ];then
                    dest_project="`echo "$repository" | awk '{print$1}'`"
                    echo "path : $CUR_DIR/$dest_project"
                    cd $CUR_DIR/$dest_project
                else
                    echo -e "\033[33merror: cannot find $*\033[0m"
                fi
            else
                cd $CUR_DIR
            fi

        else
            echo -e "\033[33merror: repo not init here!\033[0m"
        fi
        unset GREP_STRING

    else
        if [ "$1" = "-h" ];then
            Usage
        elif [ "$1" = "-v" ];then
            echo -e "\033[33mversion is:$VERSION \033[0m"
        elif [ "$1" = "-i" ];then
            Install
        elif [ "$1" = "-u" ];then
            Upgrade
        else
            cd -
        fi
    fi
else
    cd $CUR_DIR
fi
